openapi: 3.1.0
info:
  description: ""
  title: ""
  version: ""
paths: {}
components:
  responses:
    connect.error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/connect.error'
        application/proto:
          schema:
            $ref: '#/components/schemas/connect.error'
      description: ""
  schemas:
    RegisterTenantRequest:
      additionalProperties: false
      description: ""
      properties:
        email:
          additionalProperties: false
          description: ""
          format: email
          title: email
          type: string
        location:
          additionalProperties: false
          description: ""
          title: location
          type: string
        name:
          additionalProperties: false
          description: ""
          minLength: 1
          title: name
          type: string
        password:
          additionalProperties: false
          description: ""
          title: password
          type: string
      title: RegisterTenantRequest
      type: object
    RegisterTenantResponse:
      additionalProperties: false
      description: ""
      properties:
        error:
          additionalProperties: false
          description: ""
          title: error
          type: string
        status:
          additionalProperties: false
          description: ""
          title: status
          type: string
      title: RegisterTenantResponse
      type: object
    connect.error:
      additionalProperties: false
      description: 'Error type returned by Connect: https://connectrpc.com/docs/go/errors/#http-representation'
      properties:
        code:
          description: The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
          enum:
          - CodeCanceled
          - CodeUnknown
          - CodeInvalidArgument
          - CodeDeadlineExceeded
          - CodeNotFound
          - CodeAlreadyExists
          - CodePermissionDenied
          - CodeResourceExhausted
          - CodeFailedPrecondition
          - CodeAborted
          - CodeOutOfRange
          - CodeInternal
          - CodeUnavailable
          - CodeDataLoss
          - CodeUnauthenticated
          examples:
          - CodeNotFound
          type: string
        detail:
          items:
            $ref: '#/components/schemas/google.protobuf.Any'
          type: array
        message:
          description: A developer-facing error message, which should be in English.
            Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details]
            field, or localized by the client.
          type: string
      title: Connect Error
      type: object
    google.protobuf.Any:
      additionalProperties: true
      description: Contains an arbitrary serialized message along with a @type that
        describes the type of the serialized message.
      id: google.protobuf.Any
      properties:
        '@type':
          description: The type of the serialized message.
          type: string
      type: object
